id: PC55A2EBF
initial_creation_type: input
source_metadata:
  title: Amdo Geshe Jampal Rolwé Lodrö
  language: bo
  description: Texts by and about Amdo Geshe Jampal Rolwé Lodrö (a mdo dge bshes 'jam
    dpal rol ba'i blo gros, 1888–1936), a prominent Gelugpa author who composed a
    treatise on Dzogchen and appealed against sectarianism.
  volume:
    0efed0d2bffd4567a4e513181121c80e:
      title: 'The Jewelled Garland: An Aspiration for the Spread of the Teachings
        of the Omniscient Father and Son, Masters of the Teachings of the Ancient
        Translations'
      parent: Aspiration Prayers
created_at: '2022-02-28T22:39:06.515092'
last_modified_at: '2022-02-28T22:39:06.515095'
